version: '3.7'
services:

  weatherdrop:
    container_name: weatherdrop
    image: node:alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    
    restart: always
    volumes:
      - .:/app
    environment:
      - GIPHY_KEY=${GIPHY_KEY}
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
    ports:
      - 3000:3000

