{{- if (include "weatherdrop.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weatherdrop.fullname" . }}
  labels:
    {{- include "weatherdrop.labels" . | nindent 4 }}
type: Opaque
data:
  giphyKey:  {{ .Values.giphyKey | toString | b64enc | quote }}
  openWeatherApiKey:  {{ .Values.giphyKey | toString | b64enc | quote }}
{{- end }}