{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weatherdrop.serviceAccountName" . }}
  labels:
{{ include "weatherdrop.labels" . | nindent 4 }}
{{- end -}}
