apiVersion: v1
kind: Service
metadata:
  name: {{ include "weatherdrop.fullname" . }}
  labels:
    {{- include "weatherdrop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "weatherdrop.selectorLabels" . | nindent 4 }}
