name: Build Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Test
        uses: docker/build-push-action@v2.6.1
  